name: tests

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Install Bats dependencies
        run: |
          git clone https://github.com/bats-core/bats-support.git tests/test_helper/bats-support
          git clone https://github.com/bats-core/bats-assert.git tests/test_helper/bats-assert

      - name: Test Addon with DDEV
        uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}

      - name: Run Bats tests
        run: bats tests/test.bats
